/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.glb --transform 
Files: scene.glb [116.97MB] > scene-transformed.glb [2.07MB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.leaf_2_1.geometry} material={materials.leaf_2_1} position={[0.614, 3.435, 4.72]} rotation={[1.575, 0.022, -1.792]} />
      <mesh geometry={nodes.leaf_3_1.geometry} material={materials.leaf_3_1} position={[0.785, 3.855, 4.316]} rotation={[1.587, -0.034, -1.885]} />
      <mesh geometry={nodes.stones.geometry} material={materials.rocks} position={[-3.247, 0.235, -4.361]} rotation={[-1.022, 0.174, 0.315]} />
      <mesh geometry={nodes.leaf_9_1.geometry} material={materials.leaf_9_1} position={[-3.13, 0.274, -4.201]} rotation={[1.581, 0.06, -1.606]} />
      <mesh geometry={nodes.leaf_2_2.geometry} material={materials.leaf_2_2} position={[-0.407, 2.057, 2.316]} rotation={[1.261, 0.066, -1.774]} />
      <mesh geometry={nodes.leaf_3_2.geometry} material={materials.leaf_3_2} position={[2.102, 2.504, 4.669]} rotation={[1.509, -0.008, -2.072]} />
      <mesh geometry={nodes.leaf_3_3.geometry} material={materials.leaf_3_3} position={[-0.344, 2.233, 3.004]} rotation={[1.598, 0.108, -1.887]} />
      <mesh geometry={nodes.leaf_4_1.geometry} material={materials.leaf_4_1} position={[5.861, 1.401, 2.813]} rotation={[1.47, 0.036, -1.882]} />
      <mesh geometry={nodes.leaf_4_2.geometry} material={materials.leaf_4_2} position={[6.194, 1.406, 3.589]} rotation={[1.645, -0.023, -2.059]} />
      <mesh geometry={nodes.leaf_4_5.geometry} material={materials.leaf_4_5} position={[4.688, 1.367, 4.314]} rotation={[1.503, -0.251, -2.38]} />
      <mesh geometry={nodes.leaf_4_6.geometry} material={materials.leaf_4_6} position={[5.645, 1.452, 3.053]} rotation={[Math.PI / 2, 0, -2.057]} />
      <mesh geometry={nodes.leaf_4_7.geometry} material={materials.leaf_4_7} position={[6.034, 1.38, 2.971]} rotation={[1.413, 0.06, -2.018]} />
      <mesh geometry={nodes.leaf_5_1.geometry} material={materials.leaf_5_1} position={[-0.968, 0.996, 1.466]} rotation={[1.673, -0.01, -1.919]} />
      <mesh geometry={nodes.leaf_5_2.geometry} material={materials.leaf_5_2} position={[2.576, 1.257, 3.36]} rotation={[1.313, 0.08, -1.843]} />
      <mesh geometry={nodes.leaf_5_3.geometry} material={materials.leaf_5_3} position={[-0.87, 0.896, 1.209]} rotation={[1.412, 0.049, -1.893]} />
      <mesh geometry={nodes.leaf_5_4.geometry} material={materials.leaf_5_4} position={[-0.617, 0.741, 1.442]} rotation={[Math.PI / 2, 0, -1.907]} />
      <mesh geometry={nodes.leaf_6_1.geometry} material={materials.leaf_6_1} position={[0.449, 1.032, 1.91]} rotation={[1.555, -0.081, -1.931]} />
      <mesh geometry={nodes.leaf_6_2.geometry} material={materials.leaf_6_2} position={[-0.028, 0.895, 2.021]} rotation={[Math.PI / 2, 0, -1.907]} />
      <mesh geometry={nodes.leaf_6_3.geometry} material={materials.leaf_6_3} position={[0.04, 0.932, 1.741]} rotation={[1.584, 0.079, -1.884]} />
      <mesh geometry={nodes.leaf_7_1.geometry} material={materials.leaf_7_1} position={[-4.389, 1.137, -4.49]} rotation={[1.503, 0.121, -1.741]} scale={10.981} />
      <mesh geometry={nodes.leaf_7_3.geometry} material={materials.leaf_7_3} position={[-3.958, 0.91, -4.084]} rotation={[1.48, -0.041, -1.753]} scale={6.973} />
      <mesh geometry={nodes.leaf_8_1.geometry} material={materials.leaf_8_1} position={[6.251, 1.274, 3.405]} rotation={[1.822, -0.099, -1.998]} />
      <mesh geometry={nodes.leaf_8_2.geometry} material={materials.leaf_8_2} position={[-5.644, 0.414, -0.553]} rotation={[Math.PI / 2, 0, -1.907]} />
      <mesh geometry={nodes.leaf_8_3.geometry} material={materials.leaf_8_3} position={[5.925, 1.297, 2.675]} rotation={[1.341, 0.141, -1.781]} />
      <mesh geometry={nodes.leaf_8_4.geometry} material={materials.leaf_8_4} position={[5.8, 1.299, 3.704]} rotation={[Math.PI / 2, 0, -1.907]} />
      <mesh geometry={nodes.leaf_8_5.geometry} material={materials.leaf_8_5} position={[-4.802, 0.536, -0.039]} rotation={[Math.PI / 2, 0, -1.907]} />
      <mesh geometry={nodes.leaf_8_6.geometry} material={materials.leaf_8_6} position={[-4.919, 0.507, 0.177]} rotation={[Math.PI / 2, 0, -1.907]} />
      <mesh geometry={nodes.terrain.geometry} material={materials.terrain} />
      <mesh geometry={nodes.leaf_1_1.geometry} material={materials.leaf_1_1} position={[-0.745, 3.648, 3.168]} rotation={[1.071, 0.213, -1.748]} scale={6.971} />
      <mesh geometry={nodes.leaf_7_2.geometry} material={materials.leaf_7_2} position={[-4.124, 1.088, -4.216]} rotation={[1.498, 0.035, -1.746]} scale={1.822} />
      <mesh geometry={nodes.lifebuoy_2001.geometry} material={materials['circle.001']} position={[1.025, 0.226, -5.418]} rotation={[2.618, 1.093, 1.871]} />
      <mesh geometry={nodes.lighthouse.geometry} material={materials.lighthouse} position={[4.027, 1.7, 4.045]} rotation={[0, -0.211, 0]} />
      <mesh geometry={nodes.ocean.geometry} material={materials.ocean} position={[0.245, 0.081, 0.663]} />
      <mesh geometry={nodes.ocean_sky_box.geometry} material={materials.ocean_skybox} position={[0.245, -9.646, 0.663]} />
      <mesh geometry={nodes.barrel_3.geometry} material={materials.barrel} position={[3.055, 0.993, 3.225]} scale={0.1} />
      <mesh geometry={nodes.box_2.geometry} material={materials.box} position={[3.264, 1.003, 3.32]} scale={0.087} />
      <mesh geometry={nodes.dock.geometry} material={materials.dock} position={[-0.938, 0.219, -3.218]} rotation={[0, -0.543, 0]} />
      <mesh geometry={nodes.string.geometry} material={materials.string} position={[0.708, 0.183, -4.669]} rotation={[0.001, -0.145, -0.003]} />
      <mesh geometry={nodes.ship.geometry} material={materials.ship} position={[0.717, 0.223, -4.68]} rotation={[1.572, -0.003, -0.87]} />
      <mesh geometry={nodes.lifebuoy_2.geometry} material={materials.circle} position={[1.025, 0.226, -5.418]} rotation={[2.618, 1.093, 1.871]} />
      <mesh geometry={nodes.ship_origin.geometry} material={nodes.ship_origin.material} position={[0.968, 0.039, -4.976]} rotation={[0, -0.708, 0]} />
      <instancedMesh args={[nodes.Group_13001.geometry, materials.leaf_9_1, 11]} instanceMatrix={nodes.Group_13001.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13002.geometry, materials.leaf_9_1, 7]} instanceMatrix={nodes.Group_13002.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13003.geometry, materials.leaf_9_1, 6]} instanceMatrix={nodes.Group_13003.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13044.geometry, materials.leaf_9_1, 6]} instanceMatrix={nodes.Group_13044.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13066.geometry, materials.leaf_9_1, 7]} instanceMatrix={nodes.Group_13066.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13068.geometry, materials.leaf_9_1, 5]} instanceMatrix={nodes.Group_13068.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13071.geometry, materials.leaf_9_1, 7]} instanceMatrix={nodes.Group_13071.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13076.geometry, materials.leaf_9_1, 5]} instanceMatrix={nodes.Group_13076.instanceMatrix} />
      <instancedMesh args={[nodes.Group_13088.geometry, materials.leaf_9_1, 6]} instanceMatrix={nodes.Group_13088.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
